name: paig-evaluation upload to PyPI

on:
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Ensure the repo is checked out

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python3 -m pip install virtualenv
        virtualenv -p python3 venv && . venv/bin/activate
        pip install twine build pytest pytest-cov
        pip install -r paig-evaluation/paig_evaluation/requirements.txt

    - name: Test with pytest
      run: |
        filepath=$PWD
        . venv/bin/activate && cd paig-evaluation
        python3 -m pytest --cov="." --cov-report term --cov-report xml:$filepath/coverage.xml --junitxml=$filepath/junit.xml tests

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: junit-results
        path: junit.xml

    - name: Build the wheel
      run: |
        . venv/bin/activate
        cd paig-evaluation
        python3 -m build -w

    - name: Install created package
      run: |
        rm -rf venv
        virtualenv -p python3 venv && . venv/bin/activate
        cd paig-evaluation
        pip install dist/*.whl

    - name: Release to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PYPI_API_TOKEN }}
      run: |
        . venv/bin/activate
        pip install twine
        twine upload paig-evaluation/dist/*